version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  install-and-test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install
          command: ./firstTimeSetup.sh
      - run:
          name: Test
          # This assumes pytest is installed via the install-package step above
          command: ./commitBuild.sh


  publish-to-pypi:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: python -m pip install --upgrade setuptools wheel twine
      - run:
          name: verify git tag vs. version
          command: python setup.py verify
      - run:
          name: create packages
          command: python setup.py bdist_wheel
      - run:
          name: upload to pypi
          command: twine upload -u __token__ -p $PYPI_TOKEN dist/*


workflows:
  main:
    jobs:
      - install-and-test:
          filters:
            tags:
              only: /.*/
      - publish-to-pypi:
          requires:
            - install-and-test
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
